### PR TITLE
Feature/context cocktail combined

### PR DESCRIPTION
**Pull request by viteshbava**
@Paulette-Zaldivar-Flores please review this PR for my context API work.

This PR covers the following JIRA tickets:
https://viteshbava.atlassian.net/browse/EC-51
https://viteshbava.atlassian.net/browse/EC-62
https://viteshbava.atlassian.net/browse/EC-61

I think the best way to try review this is the following:
1. In the terminal run `git fetch` to fetch the latest details from the repo
2. Then run `git switch feature/context-cocktail-combined` to switch to the branch I worked on
3. If you look at App.js you'll see lines 17 & 18 commented out.  Uncomment them for this review/test.
4. Start the app: `npm start`
5. When you load the app in the browser, you should see two simple 'test components' I've created that you can use to test the Context API hook I've created.

I know the code might look a little crazy/confusing; let me know once you've made it this far and I can explain it to you when we both have time.

### CODE REVIEW

**Comment by Paulette-Zaldivar-Flores** [comment]
@viteshbava thanks for the clear instructions. I was successfully able to test this and everything looks good.

**Comment by Paulette-Zaldivar-Flores** [comment]
@viteshbava I was not sure if I should leave the code commented or not so I just left it as commented.

**Comment by Paulette-Zaldivar-Flores** [comment]
@viteshbava I tried to uncomment the code and push it but now there still seems to be a conflict. Can you spot what I am missing here?

**Comment by viteshbava** [comment]
@Paulette-Zaldivar-Flores I had to merge the develop branch into my working branch on my local (to update my working branch with the latest code in develop), and then I resolved the conflicts there.  There was a problem with the ordering of the code and Hyemi's new components.  The conflicts were resolved and I checked here again and I accidentally merged it with develop (instead of letting you do it, woops).  Feel free to test the develop branch to check it's all working okay, otherwise I think it's all good since you already checked it.

**Pull request merged**
