### PR TITLE
feature/show-search-criteria EC-109

### PR DESCRIPTION
**Pull request by Paulette-Zaldivar-Flores**
@viteshbava please review my pull request.  

To check:
- When a search is completed the number and name of cocktail is displayed above the cocktail grid.

This concerns the following ticket: https://viteshbava.atlassian.net/browse/EC-109?atlOrigin=eyJpIjoiNGE0MTExMmFhYjcwNDg0NTg5ZTQ3NGFhZGRjNWZlMzgiLCJwIjoiaiJ9

### CODE REVIEW

**Comment by viteshbava** [comment]
@Paulette-Zaldivar-Flores I see you've resolved the conflicts.  Do you want me to take a look, and if I spot anything that isn't working / isn't complete, I could just go ahead and fix them myself and get Hyemi to review the PR if you like?

**Comment by Paulette-Zaldivar-Flores** [comment]
@viteshbava yes that would be great. Thank you.

**Comment by viteshbava** [comment]
@hmshp please review this PR (I picked up this ticket from @Paulette-Zaldivar-Flores ).

The corresponding Jira ticket is EC-109

What to test / notes:
* I thought it would be useful to show the total drinks against the number currently being displayed from the filter (i.e. 'Showing x of y results for ....'
* I also added a statement when random cocktails are being displayed, that follows the same logic.
* Test the text appears correctly when random cocktails are being displayed.
* Test searching for something, and check the text appears correctly.
* Test the numbers change as expected when filters are selected/changed/cleared.
* Test the text is hidden when an error/message state is displayed (e.g. when loading, no cocktails to display, error state).

If you disagree with any of the above or spot any problems, please let me know - thanks!

**Comment by hmshp** [comment]
@viteshbava When I search for a cocktail (for example, 'gin'), a message that appears is "Showing 102 of 102 results for gin..." instead of "Showing 9 of 102". Everything other than this works as described.

**Comment by viteshbava** [comment]
@hmshp as per our Discord convo, I've improved the wording a little to make it more clear - please check and let me know if it makes a bit more sense now?  Thanks!

**Comment by hmshp** [comment]
@viteshbava It looks great! I'll merge this PR.

**Pull request merged**
