### PR TITLE
Feature/filter update - EC-108

### PR DESCRIPTION
**Pull request by viteshbava**
@hmshp please review this PR.
@Paulette-Zaldivar-Flores feel free to take a look comment as well since I had to touch some of the code you had written.

This PR covers ticket: https://viteshbava.atlassian.net/browse/EC-108 - new filters

Notes / what to test:
* Each filter, and combination of different filters selected, should be working as expected (if you can, try comparing with the data from the API to double check the logic is working as expected).
* Selecting 'Any' in any of the filters should clear that filter.
* Filters should be disabled while the cocktail list is being loaded.
* If there is an error returned when trying to retrieve the filter options, I thought it would be okay to just show empty drop down boxes (instead of an error state).  However I am logging a message to the console if an error is returned.
* Filters should remain selected when viewing cocktail details page and then returning to cocktail list.
* The Glass drop down was very long, so I added a scroll bar.
* To tidy up the code a bit, I moved some of the global styling into the /styles directory.
* I moved the Filters out of the SearchBar component and created a separate component called by CocktailListPage.js as it made more sense that way to me.

Any problems/questions please let me know - thanks!

### CODE REVIEW

**Comment by Paulette-Zaldivar-Flores** [comment]
@viteshbava I just took a look at it and everything is working as described. ☑️

**Comment by viteshbava** [comment]
Thanks @Paulette-Zaldivar-Flores !

@hmshp after your pagination PR was merged into develop, it created conflicts with this filter-update branch lol
I'll take a look and see what's wrong tomorrow.  However feel free to see if you can spot what's wrong; it's something in the CocktailList.js component, looks like your new code is causing a problem with my new filter code somewhere...

**Comment by viteshbava** [comment]
@hmshp actually I think the problem is somewhere in your code before the actual merging, we failed to test and find it before merging the PR.

I have raised a bug here with steps on how to reproduce: https://viteshbava.atlassian.net/browse/EC-116

So for this feature/filter-update PR, I would hold off from reviewing this right now until that bug is fixed.  Any problems let me know, I can try help if needed - hopefully it's a simple/obvious fix!

**Comment by viteshbava** [comment]
I'll actually close this PR and re-open it once the bug is fixed.

**Pull request closed without merging**
