### PR TITLE
Feature/search bar Jira EC- 1 and EC-31

### PR DESCRIPTION
**Pull request by Paulette-Zaldivar-Flores**
Please check for the following: 
-I can enter text into the search field.
-I can initiate the search by:
-Selecting the Button.
If search field is empty, button is inactive/greyed.  As soon as user enters text, the button becomes clickable.
-When hovering over the categories button a drop down menu appears with the categories alcoholic and non-alcoholic

Note: This pull request includes the styled logo and header. A ticket was not made for this since it is a very small task somewhat attached to this.

### CODE REVIEW

**Comment by viteshbava** [comment]
@Paulette-Zaldivar-Flores 

Sorry for the long comment!  Given we're all busy at different times I wanted to try include as much detail as possible so you don't get stuck, but let me know if you do.

1. You've requested a PR into the `<main>` branch by mistake; it should be for the `<develop>` branch.
2. When I run your branch on my local, I get a warning in the console for an "Invalid DOM property 'class'".  You just need to change `class` to `className` for some of the elements in SearchBar.js
3. When I select an option from the Categories drop down, I am taken to a new tab that opens in the browser; I think it should stay on the same tab and that category should be selected.

Also I tested a merge with develop on my local, and I found there were conflicts with some of Hyemi's changes that have been merged into develop already.  If you want to, you can try resolving these yourself before doing the PR.  If you wanted to give that a try, I've outlined instructions below.  If you don't want to / don't have time that's all good, let me know and I can take a look instead.

Note: I closed this PR as I think you'll need to create a new one anyway to merge with develop.  If you can actually keep this PR and just change main to develop somehow, feel free to Reopen.

-----------------------------------------

You can try resolving the conflicts yourself by updating your working branch on your local with the new changes and resolve the conflicts before doing the PR again (if you get stuck, let me know and I can take a look):
1. In your local machine, go to the develop branch: `git switch develop`
2. Update the develop branch with what's in the repo: `git pull`
3. If the above creates conflicts, delete you develop branch on your local: `git branch -D develop`, update your local repo: `git fetch`, then pull down the latest develop branch again: `git switch develop`.
4. Switch back to your working branch: `git switch feature/search-bar`
5. Update your working branch with develop: `git merge develop`
6. You'll probably now get the merge conflicts.
7. Most of the conflicts are in the App.js file.  Adjust the code (remove/re-order) until there are no errors.  You might need to compare it with what's currently in develop to decide where things should go.
8. I think there might also be conflicts in the package-lock.json file (I'm not sure why).  I think you can just save/accept these changes, but if you get stuck here, perhaps try deleting that file, then installing the app again (the file will be regenerated): `npm install`
9. I had a quick look at the UI after resolving the conflicts and the alignment was messed up a bit, so you may need to check.
10. Once all looks good, you can push your changes and created a new pull request against `<develop>`

**Comment by Paulette-Zaldivar-Flores** [comment]
@viteshbava thanks so much for the instructions and review. I will fix these issues and if I need help I will let you know.

**Comment by Paulette-Zaldivar-Flores** [comment]
@viteshbava i fixed the following today
1) changed class to className in SearchBar.js
2) removed target="blank" from links to avoid opening new tab
3)fixed conflicts with @hmshp code 
but still showing two errors in my terminal 😅 it says line one in App.js but I can't find the error

**Comment by viteshbava** [comment]
@Paulette-Zaldivar-Flores I pulled down your branch `feature/search-bar` from Github, and I merged it with the latest `develop` branch on my local machine, and I didn't see any conflicts or errors.  Maybe you didn't push your latest changes to Github?  Perhaps you can try again and if you still see the errors, take a screenshot and share it?

Perhaps you didn't push your latest changes because even though I get no errors, when I look at the app in the browser the alignment isn't centred as expected:

image

Also, I was looking at your code again and was wondering why you've used `<a>` tags for the options inside the drop down?  My understanding is that (to be semantically correct) `<a>` tags are normally only used when we're taking the user to another page.  In this case we don't want to do that, we just want the option in the drop down to be changed, so perhaps they should just be `<div>` tags?

**Pull request closed without merging**
